civi-download - Add composer to "bin" directory

diff --git a/bin/civi-download b/bin/civi-download
--- a/bin/civi-download
+++ b/bin/civi-download
@@ -18,7 +18,29 @@ TMPDIR="$PRJDIR/app/tmp"
 CIVIXVER=13.10.0
 CIVIXURL="http://downloads.sourceforge.net/project/civix/civix-${CIVIXVER}.tar.bz2?r=http%3A%2F%2Fsourceforge.net%2Fprojects%2Fcivix%2Ffiles%2F&use_mirror=master"
 
+##################################################
+## Helpers
+
+## download_url <url> <out-file>
+function download_url() {
+  #php -r "echo file_get_contents('$1');" > $2
+  if which wget >> /dev/null ; then
+    wget -O "$2" "$1"
+  elif which curl >> /dev/null ; then
+    curl -o "$2" "$1"
+  else
+    echo "error: failed to locate curl or wget"
+  fi
+}
+
+##################################################
 ## Validation
+php=$(which php)
+if [ -z "$php" ]; then
+  echo "Failed to locate PHP-CLI. Please install a PHP runtime and register in the PATH."
+  exit 3
+fi
+
 drush=$(which drush)
 if [ -z "$drush" ]; then
   echo "Failed to locate drush. Please install Drush (https://github.com/drush-ops/drush) and register it in the PATH."
@@ -29,27 +51,32 @@ drush | grep -qs makefile || {
  echo "Failed to locate drush-make. Plese install drush-make (https://drupal.org/project/drush_make)"; exit 1
 }
 
-if [ -d "$WEBDIR" ]; then
-  echo "Web directory ($WEBDIR) already exists. Aborting."
-  exit 2
-fi
-
 if [ ! -d "$TMPDIR" ]; then
   mkdir -p "$TMPDIR"
 fi
 
+##################################################
 ## Begin execution
 set -e
 pushd $PRJDIR >> /dev/null
-  drush make --working-copy app/config/drush.make "$WEBDIR"
-
-  if which wget >> /dev/null ; then
-    wget -O "$TMPDIR/civix.tar.bz2" "$CIVIXURL"
-  elif which curl >> /dev/null ; then
-    curl -o "$TMPDIR/civix.tar.bz2" "$CIVIXURL"
+  ## Download Drupal and dependencies
+  if [ -d "$WEBDIR" ]; then
+    echo "Web directory ($WEBDIR) already exists. Skipping."
   else
-    echo "error: failed to locate curl or wget"
+    drush make --working-copy app/config/drush.make "$WEBDIR"
   fi
+
+  ## Download composer
+  if [ -f "$PRJDIR/bin/composer" ]; then
+    echo "Composer binary ($PRJDIR/bin/composer) already exists. Skipping."
+  else
+    download_url "https://getcomposer.org/installer" "$TMPDIR/composer-installer"
+    php "$TMPDIR/composer-installer" -- --install-dir="$PRJDIR/bin"
+    mv "$PRJDIR/bin/composer.phar" "$PRJDIR/bin/composer"
+  fi
+
+  ## Download civix
+  download_url "$CIVIXURL" "$TMPDIR/civix.tar.bz2"
   mkdir -p vendor/civicrm/civix
   tar xvj  --strip-components 1 -C vendor/civicrm/civix -f "$TMPDIR/civix.tar.bz2"
   ln -s $PRJDIR/vendor/civicrm/civix/civix $PRJDIR/bin/civix
